version: '3.8'

services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: Web.Api/Dockerfiles
    ports:
      - "5000:8080"
      - "5050:8081"
    depends_on:
      - postgres  
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: HotDeskBooking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pg_data: